apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reference-production
resources:
  - ../../../kubernetes/base
patches:
  - target:
      kind: Namespace
      name: reference
    patch: |-
      - op: replace
        path: /metadata/name
        value: reference-production
commonLabels:
  app.kubernetes.io/environment: production
