apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-app
  namespace: reference-dev
  labels:
    app.kubernetes.io/name: reference-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: reference-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reference-app
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: localhost:5001/reference-app@sha256:e17a63fde89d1757f3dafb721f92c2d9fba5979ea90a86e137af2a4ba2127d9e
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_HOST
              value: "0.0.0.0"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
